### PR TITLE
Fix: Update map.bin for Route 17

### LINKED ISSUE #64: Cycling Road grass bug
No wild Pokémon are encountered in the grass on cycling road. Due to this, Eevee and other Pokémon that are supposed to appear there are currently unobtainable.

### PR DESCRIPTION
**Pull request by MrMazzone**
Update grass tiles in Route 17 to allow wild encounters. It was set to some "cycling tile grass" that was not working. Noticed other parts of the cycling road just had normal tall grass, so swapped the one patch on route 17 to have normal tall grass. 

Hopefully, fixes #64 
Would love for someone to test for me. Looking at how to compile ROM from source now. But if someone had everything set up and could test the fix, that would be great. 🙂

### CODE REVIEW

**Comment by MrMazzone** [comment]
I was able to successfully compile and test. My fix seems to work!

**Comment by DaniRainbow** [comment]
I look forward to testing this. The grass this fixes is the only place Eevee can be caught in the game

**Comment by DaniRainbow** [comment]
Works! The only pokemon that can't be obtained now is Moltres. Thanks

**Comment by MrMazzone** [comment]
Great! 🙂  Yup, that is where I left the game right now. I don't have Moltres (or Mew if they are obtainable).

Maybe this weekend I will look at if I can fix the Moltres bug.

**Comment by DaniRainbow** [comment]
@MrMazzone Did you use porymap to make these changes? If so, did you choose pokeemerald as the decomp type or pokefirered? I am using porymap and chose pokeemerald since pokeclassic is based on it but none of the maps look correct. They are all jumbled and I can't figure out how to choose pokefirered instead.

**Comment by MrMazzone** [comment]
@DaniRainbow I did use porymap set for pokeemerald and it looked like a mess. If you hover over the tiles, it says the proper type, so that is how I was able to fix it. The graphic just doesn't show properly.  I am not sure why this is. I was thinking maybe it is not mapped to the proper tileset and pokeclassic uses a variant tileset? 

Sadly, I am inexperienced with porymap and editing roms. Hoping maybe someone else can provide us with words of wisdom.

**Comment by DaniRainbow** [comment]
Thank you for the info. If the data is there I should be able to find what
I'm after.

**Comment by danenders** [comment]
You need to upgrade PoryMap to view Triple Layer Metatiles for PokeEmerald. There's a [tutorial](https://github.com/pret/pokeemerald/wiki/Triple-layer-metatiles), I'm not sure how much has changed with recent porymap updates.

**Comment by DaniRainbow** [comment]
Thank you so much! I'll do that next time I take a crack at it.

**Comment by MrMazzone** [comment]
Thank you, @danenders! Worked perfectly!

**Comment by danenders** [comment]
No worries; appreciate the work you both have been doing. I've been busy/absent but will credit you both when i get around to compiling some of these fixes into a wider release.

**Comment by danenders** [comment]
Closing this; updated the "Cycling Grass" to standard "Tall Grass". Will work on some of the other topics discussed in this thread, too.

**Pull request closed without merging**
